ai=[
    ("แมชีน เลิร์นนิ่ง","Machine Learning"),
    ("แมทชีน เลินนิ่ง","Machine Learning"),
    ("แมชชีนเลิร์นนิง","Machine Learning"),
    ("ดีพเลิร์นนิง","Deep learning"),
    ("ดีพ เลิร์นนิง","Deep learning"),
    ("ดีปเลิร์นนิง","Deep learning"),
    ("ดีพ เลินนิ่ง","Deep learning"),
    ("ดีพเลินนิ่ง","Deep learning")
]
เหรียญ=[
    ("ลูน่า","LUNA"),
    ("บิตคอยน์","Bitcoin",True),
    ("บิตคอย","Bitcoin",False),
    ("บิทคอยน์","Bitcoin",False),
    ("อีเธอเรียม","Ethereum")
]
ไอที=[
    ("ไมโครคอมพิวเตอร์","microcomputer",True),
    ("ไมโครโฟน","microphone"),
    ("โปรแกรม","program"),
    ("ซอฟต์แวร์","software"),
    ("คอมพิวเตอร์","computer"),
    ("ออนไลน์","online"),
    ("โปรแกรมเมอร์","programmer",True),
    ("โปรโตคอล","Protocol"),
    ("ดีวีดี","DVD",True),
    ("ซีดีรอม","CD ROM",True),
    ("ไอที","IT",True),
    ("อัพโหลด","upload",False),
    ("อัปโหลด","upload",True),
    ("โหลด","load",True),
    ("คลิ๊ก","Click",False),
    ("คลิก","Click",True),
    ("เกม","Game",True),
    ("เกมส์","Game",False),
    ("ฟังก์ชัน","Function",True),
    ("ฟังก์ชั่น","Function",False),
    ("ไอพี", "IP",True),
    ("โฟโต้ชอป","Photoshop",True),
    ("อะโดบี","Adobe",True),
    ("แรม","RAM",True),
    ("เมตาเวิร์ส","Metaverse",True),
    ("คริปโต","Crypto",False),
    ("คริปโท","Crypto",True),
    ("คริปโตเคอเรนซี่","Cryptocurrency",False),
    ("คริปโตเคอร์เรนซี","Cryptocurrency",False),
    ("คริปโทเคอร์เรนซี","Cryptocurrency",True),
    ("อวทาร์","avatar",True),
    ("เอนทิตี",'entity'),
    ("โฮมเพจ","home page"),
    ("ฮับ","hub"),
    ("อิมพัลส์","impulse"),
    ("อินเทอร์พรีเตอร์","interpreter"),
    ("อินทราเน็ต","intranet"),
    ("อีบุ๊ก","ebook"),
    ("อีบุ๊ก","e-book"),
    ("อีคอมเมิร์ซ","E-Commerce"),
    ("อีเลิร์นนิง","E-learning"),
    ("อีแมกะซีน","E-magazine"),
    ("ดัมมี","dummy"),
    ("ดรัม","drum"),
    ("แมโคร","macro"),
    ("เมนเฟรน","mainframe"),
    ("คีออสก์","kiosk"),
    ("เกตเวย์","gateway",True),
    ("ไอโอที","IoT",True),
    ("สตาร์ทอัพ","Startup",False),
    ("ซูเปอร์คอมพิวเตอร์","Supercomputer",True),
    ("เว็บบอร์ด","Webboard"),
    ("ไอโอเอส","iOS",True),
    ("โซเชียลเน็ตเวิร์ก","Social Network"),
    ("โซเชียลเน็ตเวิร์ค","Social Network"),
    ("โซเชียลมีเดีย","Social Media"),
    ("โมบาย","Mobile",True),
    ("แล็บท็อป","Laptop"),
    ("แล็ปท็อป","Laptop"),
    ("ลาเท็กซ์","latex"),
    ("เอ็นเอฟที","NFT"),
    ("โทเคน","token"),
    ("เอกซ์เอ็มแอล","XML"),
    ("โมเด็ม","Modem",True),
    ("เมาส์","mouse",True),
    ("เคอร์เซอร์","Cursor",True),
    ("รีเฟรช","Refresh",True),
    ("อัลตร้าไวด์","Ultra-Wide"),
    ("เทเลโฟโต้","Telephoto"),
    ("คลาวด์","Cloud"),
    ("ซิงค์","sync",True),
    ("โอดีเอฟ","ODF",True),
    ("แอพ","app",False),
    ("แอปพลิเคชัน","application",True),
    ("แอพพลิเคชั่น","application",False),
    ("จาวา","Java",True), # ภาษาคอม
    ("เฟซบุค","Facebook",False),
    ("เอแจ็กซ์","Ajax"),
    ("ฮาร์ดดิสก์","Hard Disk",True),
    ("ฮาร์ดไดรฟ์","Hard Drive"),
    ("เสิร์ชเอ็นจิ้น","Search Engine"),
    ("แชทบอท","chatbot"),
    ("เพียร์ทูเพียร์","Peer to Peer"),
    ("โดเมน","domain",True),
    ("โอเอส","OS",True),
    ("คินเดิล","Kindle"),
    ("ฟอนต์","Font"),
    ("ซีซีทีวี","CCTV"),
    ("สมาร์ตวอตช์","smart watch"),
    ("ฟลอปปีดิสก์","floppy disk"),
    ("เอชดีเอ็มไอ","HDMI")
]
สังคมออนไลน์=[ 
    ("ไลก์","like",True),
    ("ไลค์","like",False)
]
software = [
    ("ไฟร์ฟอกซ์","Firefox",True),
    ("บราวเซอร์","Browser"),
    ("กูเกิลโครม","Google Chrome"),
    ("โอเพ่นซอร์ส","open source"),
    ("แรนซัมแวร์","Ransomware"),
    ("อนาคอนดา","Anaconda"),
    ("วอร์ม","worm"),
    ("จุมลา","Joomla"),
    ("จูมล่า","Joomla"),
    ("ซีเอ็มเอส","CMS")
]

service = [
    ("กูเกิลแมป","Google Maps"),
    ("กูเกิลไดรฟ์","Google Drive"),
    ("เฟสบุ๊ค","Facebook",False),
    ("เฟสบุ๊ก","Facebook",False),
    ("เฟสบุค","Facebook",False),
    ("เฟซบุ๊ก","Facebook",True),
    ("สแนป","snap"),
    ("ทวิตเตอร์","Twitter"),
    ("อินสตาแกรม","Instagram"),
    ("เอไอจี","AIG"),
    ("ไอจี","IG"),
    ("โอเพิ่นสตรีทแมป","OpenStreetMap"),
    ("วิกิลีกส์","WikiLeaks"),
    ("วิกิพีเดีย","Wikipedia",True),
    ("ยูทูบ","youtube"),
    ("บิง","Bing"),
    ("เมตา","Meta",True),
    ("สปอติฟาย","Spotify",True),
    ("ไลน์","Line",True),
    ("วีแชต","WeChat",True),
    ("วอตส์แอปป์","WhatsApp",True),
    ("ติ๊กต็อก","TikTok")
]

it_dict=เหรียญ+software+service+ไอที+สังคมออนไลน์+ai